version:'2'

services:
  postgres:
    image:'postgres-imagen'
    build:'./postgres/'.
    cointaner_name:'psqlalpine-prn335'
    enviroment:
      - POSTGRES_USER:mortal2017
      - POSTGRES_PASSWORD:prn335
      - POSTGRES_DB:posts
    ports:
      - '5432:5432'
   

   payara:
     image:'payara-imagen'
     build:'./payara/.'
     cointainer_name:'payara-prn335'
     depends_on:
       -'postgres'
     ports:
       -'4848:4848'
       -'8080:8080'


      
 volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: